Update to WKTUI 1.5.2
oracle-livelabs/multicloud pull request #38
Opened 2023-04-25 06:25 UTC by pandey-ankit

WMS ID# 11004

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2023-04-25 13:31 UTC, ramumg requested changes
Hi @pandey-ankit, all your files and folders should have the - instead of a / 
![image](https://user-images.githubusercontent.com/84869754/234291797-a95739d1-fe1f-4aa6-906f-78d136b87999.png)
If you need to include images for this folder, please create an images folder under the main folder just like here: 
![image](https://user-images.githubusercontent.com/84869754/234292100-153f4f3e-823a-4483-a84b-147a60dbcaa4.png)

Please make these changes so we can go ahead and approve the PR. 

Thank you!

2023-04-27 01:17 UTC, ramumg requested changes
Hi @pandey-ankit, 

Please create the freetier folder under workshop 
![image](https://user-images.githubusercontent.com/84869754/234735219-843c0922-5048-4d35-b7fe-5fae01c4efee.png)

After that, we will go ahead and approve your request.

Thank you, 
Ramu

2023-04-27 05:11 UTC, pandey-ankit commented
Hi Ramu,

In your first comment, every file name contains '-', and the screenshot you shared contains two file names 'deploy-operator' and 'images'. This is not a single file name containing '/'. 

Similarly, in your second comment, the workshops folder already creates freetier folder. So what you are asking, is already there. But the representation of files creates confusion. 

Please let me know if you have any suggestions.

2023-04-27 14:43 UTC, ramumg approved these changes

2023-04-27 14:43 UTC, merged